export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_ITEMS = 'UPDATE_CART_ITEMS';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const CATEGORY_GET ="CATEGORY_GET";
export const BESTSELLER_GET ="BESTSELLER_GET";
export const NEWCOLLECTION_GET ="NEWCOLLECTION_GET";

export const PRODUCT_GET ="PRODUCT_GET";
export const PRODUCT_GETONE ="PRODUCT_GETONE";

export const CATEGORY_WISE_PRODUCT ="CATEGORY_WISE_PRODUCT";

export const PERSOLNA_DETAILS_GET ="PERSOLNA_DETAILS_GET";

export const OPEN_ADD_TO_CART="OPEN_ADD_TO_CART";

export const  IS_LOADING_TRUE = "IS_LOADING_TRUE";
export const  IS_LOADING_FALSE = "IS_LOADING_FALSE";

export const  TOGGLE_ITEM_CHECKED = "TOGGLE_ITEM_CHECKED";


